name: vision-assistant
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - opencv
  - scikit-learn
  - requests
  - python-dotenv
  - gtts
  - pip
  - pip:
    - speechrecognition
    - openai
    - pyaudio
    - ultralytics  # for YOLOv8
    - python-dateutil
    - spellchecker
    - pyspellchecker
    - mamba  # for environment management
    - homeassistant-api  # for Home Assistant integration
    - python-homeassistant-api  # alternative Home Assistant client
    - websockets  # required for Home Assistant
    - aiohttp  # required for Home Assistant
    - asyncio  # required for Home Assistant 